// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/interpreter/interfaces/interfaces.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	context "context"
	time "time"

	gomock "github.com/golang/mock/gomock"
	iwfidl "github.com/indeedeng/iwf/gen/iwfidl"
	service "github.com/indeedeng/iwf/service"
)

// MockActivityProvider is a mock of ActivityProvider interface.
type MockActivityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockActivityProviderMockRecorder
}

// MockActivityProviderMockRecorder is the mock recorder for MockActivityProvider.
type MockActivityProviderMockRecorder struct {
	mock *MockActivityProvider
}

// NewMockActivityProvider creates a new mock instance.
func NewMockActivityProvider(ctrl *gomock.Controller) *MockActivityProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityProvider) EXPECT() *MockActivityProviderMockRecorder {
	_ = "STUB: not implemented"

	// GetActivityInfo mocks base method.
	return nil
}

func (m *MockActivityProvider) GetActivityInfo(ctx context.Context) ActivityInfo {
	_ = "STUB: not implemented"
	return *new(ActivityInfo)
}

// GetActivityInfo indicates an expected call of GetActivityInfo.
func (mr *MockActivityProviderMockRecorder) GetActivityInfo(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLogger mocks base method.
func (m *MockActivityProvider) GetLogger(ctx context.Context) UnifiedLogger {
	_ = "STUB: not implemented"
	return *new(UnifiedLogger)
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockActivityProviderMockRecorder) GetLogger(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewApplicationError mocks base method.
func (m *MockActivityProvider) NewApplicationError(errType string, details interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// NewApplicationError indicates an expected call of NewApplicationError.
func (mr *MockActivityProviderMockRecorder) NewApplicationError(errType, details interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecordHeartbeat mocks base method.
func (m *MockActivityProvider) RecordHeartbeat(ctx context.Context, details ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// RecordHeartbeat indicates an expected call of RecordHeartbeat.
func (mr *MockActivityProviderMockRecorder) RecordHeartbeat(ctx interface{}, details ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockUnifiedLogger is a mock of UnifiedLogger interface.
type MockUnifiedLogger struct {
	ctrl     *gomock.Controller
	recorder *MockUnifiedLoggerMockRecorder
}

// MockUnifiedLoggerMockRecorder is the mock recorder for MockUnifiedLogger.
type MockUnifiedLoggerMockRecorder struct {
	mock *MockUnifiedLogger
}

// NewMockUnifiedLogger creates a new mock instance.
func NewMockUnifiedLogger(ctrl *gomock.Controller) *MockUnifiedLogger {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnifiedLogger) EXPECT() *MockUnifiedLoggerMockRecorder {
	_ = "STUB: not implemented"

	// Debug mocks base method.
	return nil
}

func (m *MockUnifiedLogger) Debug(msg string, keyvals ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Debug indicates an expected call of Debug.
func (mr *MockUnifiedLoggerMockRecorder) Debug(msg interface{}, keyvals ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Error mocks base method.
func (m *MockUnifiedLogger) Error(msg string, keyvals ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Error indicates an expected call of Error.
func (mr *MockUnifiedLoggerMockRecorder) Error(msg interface{}, keyvals ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Info mocks base method.
func (m *MockUnifiedLogger) Info(msg string, keyvals ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Info indicates an expected call of Info.
func (mr *MockUnifiedLoggerMockRecorder) Info(msg interface{}, keyvals ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Warn mocks base method.
func (m *MockUnifiedLogger) Warn(msg string, keyvals ...interface{}) {
	_ = "STUB: not implemented"
	return
}

// Warn indicates an expected call of Warn.
func (mr *MockUnifiedLoggerMockRecorder) Warn(msg interface{}, keyvals ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockUnifiedContext is a mock of UnifiedContext interface.
type MockUnifiedContext struct {
	ctrl     *gomock.Controller
	recorder *MockUnifiedContextMockRecorder
}

// MockUnifiedContextMockRecorder is the mock recorder for MockUnifiedContext.
type MockUnifiedContextMockRecorder struct {
	mock *MockUnifiedContext
}

// NewMockUnifiedContext creates a new mock instance.
func NewMockUnifiedContext(ctrl *gomock.Controller) *MockUnifiedContext {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnifiedContext) EXPECT() *MockUnifiedContextMockRecorder {
	_ = "STUB: not implemented"

	// GetContext mocks base method.
	return nil
}

func (m *MockUnifiedContext) GetContext() interface{} { _ = "STUB: not implemented"; return nil }

// GetContext indicates an expected call of GetContext.
func (mr *MockUnifiedContextMockRecorder) GetContext() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTimerProcessor is a mock of TimerProcessor interface.
type MockTimerProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTimerProcessorMockRecorder
}

// MockTimerProcessorMockRecorder is the mock recorder for MockTimerProcessor.
type MockTimerProcessorMockRecorder struct {
	mock *MockTimerProcessor
}

// NewMockTimerProcessor creates a new mock instance.
func NewMockTimerProcessor(ctrl *gomock.Controller) *MockTimerProcessor {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimerProcessor) EXPECT() *MockTimerProcessorMockRecorder {
	_ = "STUB: not implemented"

	// AddTimers mocks base method.
	return nil
}

func (m *MockTimerProcessor) AddTimers(stateExeId string, commands []iwfidl.TimerCommand, completedTimerCmds map[int]service.InternalTimerStatus) {
	_ = "STUB: not implemented"
	return
}

// AddTimers indicates an expected call of AddTimers.
func (mr *MockTimerProcessorMockRecorder) AddTimers(stateExeId, commands, completedTimerCmds interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Dump mocks base method.
func (m *MockTimerProcessor) Dump() []service.StaleSkipTimerSignal {
	_ = "STUB: not implemented"
	return nil
}

// Dump indicates an expected call of Dump.
func (mr *MockTimerProcessorMockRecorder) Dump() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTimerInfos mocks base method.
func (m *MockTimerProcessor) GetTimerInfos() map[string][]*service.TimerInfo {
	_ = "STUB: not implemented"
	return nil
}

// GetTimerInfos indicates an expected call of GetTimerInfos.
func (mr *MockTimerProcessorMockRecorder) GetTimerInfos() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTimerStartedUnixTimestamps mocks base method.
func (m *MockTimerProcessor) GetTimerStartedUnixTimestamps() []int64 {
	_ = "STUB: not implemented"
	return nil
}

// GetTimerStartedUnixTimestamps indicates an expected call of GetTimerStartedUnixTimestamps.
func (mr *MockTimerProcessorMockRecorder) GetTimerStartedUnixTimestamps() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemovePendingTimersOfState mocks base method.
func (m *MockTimerProcessor) RemovePendingTimersOfState(stateExeId string) {
	_ = "STUB: not implemented"
	return
}

// RemovePendingTimersOfState indicates an expected call of RemovePendingTimersOfState.
func (mr *MockTimerProcessorMockRecorder) RemovePendingTimersOfState(stateExeId interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RetryStaleSkipTimer mocks base method.
func (m *MockTimerProcessor) RetryStaleSkipTimer() bool { _ = "STUB: not implemented"; return false }

// RetryStaleSkipTimer indicates an expected call of RetryStaleSkipTimer.
func (mr *MockTimerProcessorMockRecorder) RetryStaleSkipTimer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SkipTimer mocks base method.
func (m *MockTimerProcessor) SkipTimer(stateExeId, timerId string, timerIdx int) bool {
	_ = "STUB: not implemented"
	return false
}

// SkipTimer indicates an expected call of SkipTimer.
func (mr *MockTimerProcessorMockRecorder) SkipTimer(stateExeId, timerId, timerIdx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForTimerFiredOrSkipped mocks base method.
func (m *MockTimerProcessor) WaitForTimerFiredOrSkipped(ctx UnifiedContext, stateExeId string, timerIdx int, cancelWaiting *bool) service.InternalTimerStatus {
	_ = "STUB: not implemented"
	return *new(service.InternalTimerStatus)
}

// WaitForTimerFiredOrSkipped indicates an expected call of WaitForTimerFiredOrSkipped.
func (mr *MockTimerProcessorMockRecorder) WaitForTimerFiredOrSkipped(ctx, stateExeId, timerIdx, cancelWaiting interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockWorkflowProvider is a mock of WorkflowProvider interface.
type MockWorkflowProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowProviderMockRecorder
}

// MockWorkflowProviderMockRecorder is the mock recorder for MockWorkflowProvider.
type MockWorkflowProviderMockRecorder struct {
	mock *MockWorkflowProvider
}

// NewMockWorkflowProvider creates a new mock instance.
func NewMockWorkflowProvider(ctrl *gomock.Controller) *MockWorkflowProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowProvider) EXPECT() *MockWorkflowProviderMockRecorder {
	_ = "STUB: not implemented"

	// Await mocks base method.
	return nil
}

func (m *MockWorkflowProvider) Await(ctx UnifiedContext, condition func() bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Await indicates an expected call of Await.
func (mr *MockWorkflowProviderMockRecorder) Await(ctx, condition interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteActivity mocks base method.
func (m *MockWorkflowProvider) ExecuteActivity(valuePtr interface{}, optimizeByLocalActivity bool, ctx UnifiedContext, activity interface{}, args ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteActivity indicates an expected call of ExecuteActivity.
func (mr *MockWorkflowProviderMockRecorder) ExecuteActivity(valuePtr, optimizeByLocalActivity, ctx, activity interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteLocalActivity mocks base method.
func (m *MockWorkflowProvider) ExecuteLocalActivity(valuePtr interface{}, ctx UnifiedContext, activity interface{}, args ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteLocalActivity indicates an expected call of ExecuteLocalActivity.
func (mr *MockWorkflowProviderMockRecorder) ExecuteLocalActivity(valuePtr, ctx, activity interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExtendContextWithValue mocks base method.
func (m *MockWorkflowProvider) ExtendContextWithValue(parent UnifiedContext, key string, val interface{}) UnifiedContext {
	_ = "STUB: not implemented"
	return *new(UnifiedContext)
}

// ExtendContextWithValue indicates an expected call of ExtendContextWithValue.
func (mr *MockWorkflowProviderMockRecorder) ExtendContextWithValue(parent, key, val interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBackendType mocks base method.
func (m *MockWorkflowProvider) GetBackendType() service.BackendType {
	_ = "STUB: not implemented"
	return *new(service.BackendType)
}

// GetBackendType indicates an expected call of GetBackendType.
func (mr *MockWorkflowProviderMockRecorder) GetBackendType() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetContextValue mocks base method.
func (m *MockWorkflowProvider) GetContextValue(ctx UnifiedContext, key string) interface{} {
	_ = "STUB: not implemented"
	return nil
}

// GetContextValue indicates an expected call of GetContextValue.
func (mr *MockWorkflowProviderMockRecorder) GetContextValue(ctx, key interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLogger mocks base method.
func (m *MockWorkflowProvider) GetLogger(ctx UnifiedContext) UnifiedLogger {
	_ = "STUB: not implemented"
	return *new(UnifiedLogger)
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockWorkflowProviderMockRecorder) GetLogger(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPendingThreadNames mocks base method.
func (m *MockWorkflowProvider) GetPendingThreadNames() map[string]int {
	_ = "STUB: not implemented"
	return nil
}

// GetPendingThreadNames indicates an expected call of GetPendingThreadNames.
func (mr *MockWorkflowProviderMockRecorder) GetPendingThreadNames() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSearchAttributes mocks base method.
func (m *MockWorkflowProvider) GetSearchAttributes(ctx UnifiedContext, requestedSearchAttributes []iwfidl.SearchAttributeKeyAndType) (map[string]iwfidl.SearchAttribute, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSearchAttributes indicates an expected call of GetSearchAttributes.
func (mr *MockWorkflowProviderMockRecorder) GetSearchAttributes(ctx, requestedSearchAttributes interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSignalChannel mocks base method.
func (m *MockWorkflowProvider) GetSignalChannel(ctx UnifiedContext, signalName string) ReceiveChannel {
	_ = "STUB: not implemented"
	return *new(ReceiveChannel)
}

// GetSignalChannel indicates an expected call of GetSignalChannel.
func (mr *MockWorkflowProviderMockRecorder) GetSignalChannel(ctx, signalName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetThreadCount mocks base method.
func (m *MockWorkflowProvider) GetThreadCount() int { _ = "STUB: not implemented"; return 0 }

// GetThreadCount indicates an expected call of GetThreadCount.
func (mr *MockWorkflowProviderMockRecorder) GetThreadCount() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUnhandledSignalNames mocks base method.
func (m *MockWorkflowProvider) GetUnhandledSignalNames(ctx UnifiedContext) []string {
	_ = "STUB: not implemented"
	return nil
}

// GetUnhandledSignalNames indicates an expected call of GetUnhandledSignalNames.
func (mr *MockWorkflowProviderMockRecorder) GetUnhandledSignalNames(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVersion mocks base method.
func (m *MockWorkflowProvider) GetVersion(ctx UnifiedContext, changeID string, minSupported, maxSupported int) int {
	_ = "STUB: not implemented"
	return 0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockWorkflowProviderMockRecorder) GetVersion(ctx, changeID, minSupported, maxSupported interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkflowInfo mocks base method.
func (m *MockWorkflowProvider) GetWorkflowInfo(ctx UnifiedContext) WorkflowInfo {
	_ = "STUB: not implemented"
	return *new(WorkflowInfo)
}

// GetWorkflowInfo indicates an expected call of GetWorkflowInfo.
func (mr *MockWorkflowProviderMockRecorder) GetWorkflowInfo(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GoNamed mocks base method.
func (m *MockWorkflowProvider) GoNamed(ctx UnifiedContext, name string, f func(UnifiedContext)) {
	_ = "STUB: not implemented"
	return
}

// GoNamed indicates an expected call of GoNamed.
func (mr *MockWorkflowProviderMockRecorder) GoNamed(ctx, name, f interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsApplicationError mocks base method.
func (m *MockWorkflowProvider) IsApplicationError(err error) bool {
	_ = "STUB: not implemented"
	return false
}

// IsApplicationError indicates an expected call of IsApplicationError.
func (mr *MockWorkflowProviderMockRecorder) IsApplicationError(err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsReplaying mocks base method.
func (m *MockWorkflowProvider) IsReplaying(ctx UnifiedContext) bool {
	_ = "STUB: not implemented"
	return false
}

// IsReplaying indicates an expected call of IsReplaying.
func (mr *MockWorkflowProviderMockRecorder) IsReplaying(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewApplicationError mocks base method.
func (m *MockWorkflowProvider) NewApplicationError(errType string, details interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// NewApplicationError indicates an expected call of NewApplicationError.
func (mr *MockWorkflowProviderMockRecorder) NewApplicationError(errType, details interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewInterpreterContinueAsNewError mocks base method.
func (m *MockWorkflowProvider) NewInterpreterContinueAsNewError(ctx UnifiedContext, input service.InterpreterWorkflowInput) error {
	_ = "STUB: not implemented"
	return nil
}

// NewInterpreterContinueAsNewError indicates an expected call of NewInterpreterContinueAsNewError.
func (mr *MockWorkflowProviderMockRecorder) NewInterpreterContinueAsNewError(ctx, input interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewTimer mocks base method.
func (m *MockWorkflowProvider) NewTimer(ctx UnifiedContext, d time.Duration) Future {
	_ = "STUB: not implemented"
	return *new(Future)
}

// NewTimer indicates an expected call of NewTimer.
func (mr *MockWorkflowProviderMockRecorder) NewTimer(ctx, d interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Now mocks base method.
func (m *MockWorkflowProvider) Now(ctx UnifiedContext) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// Now indicates an expected call of Now.
func (mr *MockWorkflowProviderMockRecorder) Now(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetQueryHandler mocks base method.
func (m *MockWorkflowProvider) SetQueryHandler(ctx UnifiedContext, queryType string, handler interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SetQueryHandler indicates an expected call of SetQueryHandler.
func (mr *MockWorkflowProviderMockRecorder) SetQueryHandler(ctx, queryType, handler interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetRpcUpdateHandler mocks base method.
func (m *MockWorkflowProvider) SetRpcUpdateHandler(ctx UnifiedContext, updateType string, validator UnifiedRpcValidator, handler UnifiedRpcHandler) error {
	_ = "STUB: not implemented"
	return nil
}

// SetRpcUpdateHandler indicates an expected call of SetRpcUpdateHandler.
func (mr *MockWorkflowProviderMockRecorder) SetRpcUpdateHandler(ctx, updateType, validator, handler interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Sleep mocks base method.
func (m *MockWorkflowProvider) Sleep(ctx UnifiedContext, d time.Duration) error {
	_ = "STUB: not implemented"
	return nil
}

// Sleep indicates an expected call of Sleep.
func (mr *MockWorkflowProviderMockRecorder) Sleep(ctx, d interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpsertMemo mocks base method.
func (m *MockWorkflowProvider) UpsertMemo(ctx UnifiedContext, memo map[string]iwfidl.EncodedObject) error {
	_ = "STUB: not implemented"
	return nil
}

// UpsertMemo indicates an expected call of UpsertMemo.
func (mr *MockWorkflowProviderMockRecorder) UpsertMemo(ctx, memo interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpsertSearchAttributes mocks base method.
func (m *MockWorkflowProvider) UpsertSearchAttributes(ctx UnifiedContext, attributes map[string]interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// UpsertSearchAttributes indicates an expected call of UpsertSearchAttributes.
func (mr *MockWorkflowProviderMockRecorder) UpsertSearchAttributes(ctx, attributes interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WithActivityOptions mocks base method.
func (m *MockWorkflowProvider) WithActivityOptions(ctx UnifiedContext, options ActivityOptions) UnifiedContext {
	_ = "STUB: not implemented"
	return *new(UnifiedContext)
}

// WithActivityOptions indicates an expected call of WithActivityOptions.
func (mr *MockWorkflowProviderMockRecorder) WithActivityOptions(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReceiveChannel is a mock of ReceiveChannel interface.
type MockReceiveChannel struct {
	ctrl     *gomock.Controller
	recorder *MockReceiveChannelMockRecorder
}

// MockReceiveChannelMockRecorder is the mock recorder for MockReceiveChannel.
type MockReceiveChannelMockRecorder struct {
	mock *MockReceiveChannel
}

// NewMockReceiveChannel creates a new mock instance.
func NewMockReceiveChannel(ctrl *gomock.Controller) *MockReceiveChannel {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiveChannel) EXPECT() *MockReceiveChannelMockRecorder {
	_ = "STUB: not implemented"

	// ReceiveAsync mocks base method.
	return nil
}

func (m *MockReceiveChannel) ReceiveAsync(valuePtr interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

// ReceiveAsync indicates an expected call of ReceiveAsync.
func (mr *MockReceiveChannelMockRecorder) ReceiveAsync(valuePtr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReceiveBlocking mocks base method.
func (m *MockReceiveChannel) ReceiveBlocking(ctx UnifiedContext, valuePtr interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

// ReceiveBlocking indicates an expected call of ReceiveBlocking.
func (mr *MockReceiveChannelMockRecorder) ReceiveBlocking(ctx, valuePtr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockFuture is a mock of Future interface.
type MockFuture struct {
	ctrl     *gomock.Controller
	recorder *MockFutureMockRecorder
}

// MockFutureMockRecorder is the mock recorder for MockFuture.
type MockFutureMockRecorder struct {
	mock *MockFuture
}

// NewMockFuture creates a new mock instance.
func NewMockFuture(ctrl *gomock.Controller) *MockFuture { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuture) EXPECT() *MockFutureMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockFuture) Get(ctx UnifiedContext, valuePtr interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Get indicates an expected call of Get.
func (mr *MockFutureMockRecorder) Get(ctx, valuePtr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsReady mocks base method.
func (m *MockFuture) IsReady() bool { _ = "STUB: not implemented"; return false }

// IsReady indicates an expected call of IsReady.
func (mr *MockFutureMockRecorder) IsReady() *gomock.Call { _ = "STUB: not implemented"; return nil }
