// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/qlong/indeed/temporoio/sdk-go/converter/data_converter.go

// Package temporal is a generated GoMock package.
package temporal

import (
	gomock "github.com/golang/mock/gomock"
	common "go.temporal.io/api/common/v1"
)

// MockDataConverter is a mock of DataConverter interface.
type MockDataConverter struct {
	ctrl     *gomock.Controller
	recorder *MockDataConverterMockRecorder
}

// MockDataConverterMockRecorder is the mock recorder for MockDataConverter.
type MockDataConverterMockRecorder struct {
	mock *MockDataConverter
}

// NewMockDataConverter creates a new mock instance.
func NewMockDataConverter(ctrl *gomock.Controller) *MockDataConverter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataConverter) EXPECT() *MockDataConverterMockRecorder {
	_ = "STUB: not implemented"

	// FromPayload mocks base method.
	return nil
}

func (m *MockDataConverter) FromPayload(payload *common.Payload, valuePtr interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// FromPayload indicates an expected call of FromPayload.
func (mr *MockDataConverterMockRecorder) FromPayload(payload, valuePtr interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FromPayloads mocks base method.
func (m *MockDataConverter) FromPayloads(payloads *common.Payloads, valuePtrs ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// FromPayloads indicates an expected call of FromPayloads.
func (mr *MockDataConverterMockRecorder) FromPayloads(payloads interface{}, valuePtrs ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToPayload mocks base method.
func (m *MockDataConverter) ToPayload(value interface{}) (*common.Payload, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ToPayload indicates an expected call of ToPayload.
func (mr *MockDataConverterMockRecorder) ToPayload(value interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToPayloads mocks base method.
func (m *MockDataConverter) ToPayloads(value ...interface{}) (*common.Payloads, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ToPayloads indicates an expected call of ToPayloads.
func (mr *MockDataConverterMockRecorder) ToPayloads(value ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToString mocks base method.
func (m *MockDataConverter) ToString(input *common.Payload) string {
	_ = "STUB: not implemented"
	return ""
}

// ToString indicates an expected call of ToString.
func (mr *MockDataConverterMockRecorder) ToString(input interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ToStrings mocks base method.
func (m *MockDataConverter) ToStrings(input *common.Payloads) []string {
	_ = "STUB: not implemented"
	return nil
}

// ToStrings indicates an expected call of ToStrings.
func (mr *MockDataConverterMockRecorder) ToStrings(input interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
