// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/lwolczynski/temporalio/sdk-go/client/client.go

// Package temporal is a generated GoMock package.
package temporal

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	cloudservice "go.temporal.io/api/cloud/cloudservice/v1"
	enums "go.temporal.io/api/enums/v1"
	operatorservice "go.temporal.io/api/operatorservice/v1"
	workflowservice "go.temporal.io/api/workflowservice/v1"
	client "go.temporal.io/sdk/client"
	converter "go.temporal.io/sdk/converter"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// CancelWorkflow mocks base method.
	return nil
}

func (m *MockClient) CancelWorkflow(ctx context.Context, workflowID, runID string) error {
	_ = "STUB: not implemented"
	return nil
}

// CancelWorkflow indicates an expected call of CancelWorkflow.
func (mr *MockClientMockRecorder) CancelWorkflow(ctx, workflowID, runID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CheckHealth mocks base method.
func (m *MockClient) CheckHealth(ctx context.Context, request *client.CheckHealthRequest) (*client.CheckHealthResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockClientMockRecorder) CheckHealth(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockClient) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// CompleteActivity mocks base method.
func (m *MockClient) CompleteActivity(ctx context.Context, taskToken []byte, result interface{}, err error) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivity indicates an expected call of CompleteActivity.
func (mr *MockClientMockRecorder) CompleteActivity(ctx, taskToken, result, err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByID mocks base method.
func (m *MockClient) CompleteActivityByID(ctx context.Context, namespace, workflowID, runID, activityID string, result interface{}, err error) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByID indicates an expected call of CompleteActivityByID.
func (mr *MockClientMockRecorder) CompleteActivityByID(ctx, namespace, workflowID, runID, activityID, result, err interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CountWorkflow mocks base method.
func (m *MockClient) CountWorkflow(ctx context.Context, request *workflowservice.CountWorkflowExecutionsRequest) (*workflowservice.CountWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CountWorkflow indicates an expected call of CountWorkflow.
func (mr *MockClientMockRecorder) CountWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeTaskQueue mocks base method.
func (m *MockClient) DescribeTaskQueue(ctx context.Context, taskqueue string, taskqueueType enums.TaskQueueType) (*workflowservice.DescribeTaskQueueResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeTaskQueue indicates an expected call of DescribeTaskQueue.
func (mr *MockClientMockRecorder) DescribeTaskQueue(ctx, taskqueue, taskqueueType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeTaskQueueEnhanced mocks base method.
func (m *MockClient) DescribeTaskQueueEnhanced(ctx context.Context, options client.DescribeTaskQueueEnhancedOptions) (client.TaskQueueDescription, error) {
	_ = "STUB: not implemented"
	return *new(client.TaskQueueDescription), nil
}

// DescribeTaskQueueEnhanced indicates an expected call of DescribeTaskQueueEnhanced.
func (mr *MockClientMockRecorder) DescribeTaskQueueEnhanced(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeWorkflowExecution mocks base method.
func (m *MockClient) DescribeWorkflowExecution(ctx context.Context, workflowID, runID string) (*workflowservice.DescribeWorkflowExecutionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeWorkflowExecution indicates an expected call of DescribeWorkflowExecution.
func (mr *MockClientMockRecorder) DescribeWorkflowExecution(ctx, workflowID, runID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteWorkflow mocks base method.
func (m *MockClient) ExecuteWorkflow(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun), nil
}

// ExecuteWorkflow indicates an expected call of ExecuteWorkflow.
func (mr *MockClientMockRecorder) ExecuteWorkflow(ctx, options, workflow interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSearchAttributes mocks base method.
func (m *MockClient) GetSearchAttributes(ctx context.Context) (*workflowservice.GetSearchAttributesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSearchAttributes indicates an expected call of GetSearchAttributes.
func (mr *MockClientMockRecorder) GetSearchAttributes(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkerBuildIdCompatibility mocks base method.
func (m *MockClient) GetWorkerBuildIdCompatibility(ctx context.Context, options *client.GetWorkerBuildIdCompatibilityOptions) (*client.WorkerBuildIDVersionSets, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetWorkerBuildIdCompatibility indicates an expected call of GetWorkerBuildIdCompatibility.
func (mr *MockClientMockRecorder) GetWorkerBuildIdCompatibility(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkerTaskReachability mocks base method.
func (m *MockClient) GetWorkerTaskReachability(ctx context.Context, options *client.GetWorkerTaskReachabilityOptions) (*client.WorkerTaskReachability, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetWorkerTaskReachability indicates an expected call of GetWorkerTaskReachability.
func (mr *MockClientMockRecorder) GetWorkerTaskReachability(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkerVersioningRules mocks base method.
func (m *MockClient) GetWorkerVersioningRules(ctx context.Context, options client.GetWorkerVersioningOptions) (*client.WorkerVersioningRules, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetWorkerVersioningRules indicates an expected call of GetWorkerVersioningRules.
func (mr *MockClientMockRecorder) GetWorkerVersioningRules(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkflow mocks base method.
func (m *MockClient) GetWorkflow(ctx context.Context, workflowID, runID string) client.WorkflowRun {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun)
}

// GetWorkflow indicates an expected call of GetWorkflow.
func (mr *MockClientMockRecorder) GetWorkflow(ctx, workflowID, runID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkflowHistory mocks base method.
func (m *MockClient) GetWorkflowHistory(ctx context.Context, workflowID, runID string, isLongPoll bool, filterType enums.HistoryEventFilterType) client.HistoryEventIterator {
	_ = "STUB: not implemented"
	return *new(client.HistoryEventIterator)
}

// GetWorkflowHistory indicates an expected call of GetWorkflowHistory.
func (mr *MockClientMockRecorder) GetWorkflowHistory(ctx, workflowID, runID, isLongPoll, filterType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWorkflowUpdateHandle mocks base method.
func (m *MockClient) GetWorkflowUpdateHandle(ref client.GetWorkflowUpdateHandleOptions) client.WorkflowUpdateHandle {
	_ = "STUB: not implemented"
	return *new(client.WorkflowUpdateHandle)
}

// GetWorkflowUpdateHandle indicates an expected call of GetWorkflowUpdateHandle.
func (mr *MockClientMockRecorder) GetWorkflowUpdateHandle(ref interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListArchivedWorkflow mocks base method.
func (m *MockClient) ListArchivedWorkflow(ctx context.Context, request *workflowservice.ListArchivedWorkflowExecutionsRequest) (*workflowservice.ListArchivedWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListArchivedWorkflow indicates an expected call of ListArchivedWorkflow.
func (mr *MockClientMockRecorder) ListArchivedWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListClosedWorkflow mocks base method.
func (m *MockClient) ListClosedWorkflow(ctx context.Context, request *workflowservice.ListClosedWorkflowExecutionsRequest) (*workflowservice.ListClosedWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListClosedWorkflow indicates an expected call of ListClosedWorkflow.
func (mr *MockClientMockRecorder) ListClosedWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListOpenWorkflow mocks base method.
func (m *MockClient) ListOpenWorkflow(ctx context.Context, request *workflowservice.ListOpenWorkflowExecutionsRequest) (*workflowservice.ListOpenWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOpenWorkflow indicates an expected call of ListOpenWorkflow.
func (mr *MockClientMockRecorder) ListOpenWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListWorkflow mocks base method.
func (m *MockClient) ListWorkflow(ctx context.Context, request *workflowservice.ListWorkflowExecutionsRequest) (*workflowservice.ListWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListWorkflow indicates an expected call of ListWorkflow.
func (mr *MockClientMockRecorder) ListWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OperatorService mocks base method.
func (m *MockClient) OperatorService() operatorservice.OperatorServiceClient {
	_ = "STUB: not implemented"
	return *new(operatorservice.OperatorServiceClient)
}

// OperatorService indicates an expected call of OperatorService.
func (mr *MockClientMockRecorder) OperatorService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryWorkflow mocks base method.
func (m *MockClient) QueryWorkflow(ctx context.Context, workflowID, runID, queryType string, args ...interface{}) (converter.EncodedValue, error) {
	_ = "STUB: not implemented"
	return *new(converter.EncodedValue), nil
}

// QueryWorkflow indicates an expected call of QueryWorkflow.
func (mr *MockClientMockRecorder) QueryWorkflow(ctx, workflowID, runID, queryType interface{}, args ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryWorkflowWithOptions mocks base method.
func (m *MockClient) QueryWorkflowWithOptions(ctx context.Context, request *client.QueryWorkflowWithOptionsRequest) (*client.QueryWorkflowWithOptionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryWorkflowWithOptions indicates an expected call of QueryWorkflowWithOptions.
func (mr *MockClientMockRecorder) QueryWorkflowWithOptions(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeat mocks base method.
func (m *MockClient) RecordActivityHeartbeat(ctx context.Context, taskToken []byte, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeat indicates an expected call of RecordActivityHeartbeat.
func (mr *MockClientMockRecorder) RecordActivityHeartbeat(ctx, taskToken interface{}, details ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeatByID mocks base method.
func (m *MockClient) RecordActivityHeartbeatByID(ctx context.Context, namespace, workflowID, runID, activityID string, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeatByID indicates an expected call of RecordActivityHeartbeatByID.
func (mr *MockClientMockRecorder) RecordActivityHeartbeatByID(ctx, namespace, workflowID, runID, activityID interface{}, details ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetWorkflowExecution mocks base method.
func (m *MockClient) ResetWorkflowExecution(ctx context.Context, request *workflowservice.ResetWorkflowExecutionRequest) (*workflowservice.ResetWorkflowExecutionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetWorkflowExecution indicates an expected call of ResetWorkflowExecution.
func (mr *MockClientMockRecorder) ResetWorkflowExecution(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ScanWorkflow mocks base method.
func (m *MockClient) ScanWorkflow(ctx context.Context, request *workflowservice.ScanWorkflowExecutionsRequest) (*workflowservice.ScanWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ScanWorkflow indicates an expected call of ScanWorkflow.
func (mr *MockClientMockRecorder) ScanWorkflow(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ScheduleClient mocks base method.
func (m *MockClient) ScheduleClient() client.ScheduleClient {
	_ = "STUB: not implemented"
	return *new(client.ScheduleClient)
}

// ScheduleClient indicates an expected call of ScheduleClient.
func (mr *MockClientMockRecorder) ScheduleClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SignalWithStartWorkflow mocks base method.
func (m *MockClient) SignalWithStartWorkflow(ctx context.Context, workflowID, signalName string, signalArg interface{}, options client.StartWorkflowOptions, workflow interface{}, workflowArgs ...interface{}) (client.WorkflowRun, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun), nil
}

// SignalWithStartWorkflow indicates an expected call of SignalWithStartWorkflow.
func (mr *MockClientMockRecorder) SignalWithStartWorkflow(ctx, workflowID, signalName, signalArg, options, workflow interface{}, workflowArgs ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SignalWorkflow mocks base method.
func (m *MockClient) SignalWorkflow(ctx context.Context, workflowID, runID, signalName string, arg interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SignalWorkflow indicates an expected call of SignalWorkflow.
func (mr *MockClientMockRecorder) SignalWorkflow(ctx, workflowID, runID, signalName, arg interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TerminateWorkflow mocks base method.
func (m *MockClient) TerminateWorkflow(ctx context.Context, workflowID, runID, reason string, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// TerminateWorkflow indicates an expected call of TerminateWorkflow.
func (mr *MockClientMockRecorder) TerminateWorkflow(ctx, workflowID, runID, reason interface{}, details ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWorkerBuildIdCompatibility mocks base method.
func (m *MockClient) UpdateWorkerBuildIdCompatibility(ctx context.Context, options *client.UpdateWorkerBuildIdCompatibilityOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWorkerBuildIdCompatibility indicates an expected call of UpdateWorkerBuildIdCompatibility.
func (mr *MockClientMockRecorder) UpdateWorkerBuildIdCompatibility(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWorkerVersioningRules mocks base method.
func (m *MockClient) UpdateWorkerVersioningRules(ctx context.Context, options client.UpdateWorkerVersioningRulesOptions) (*client.WorkerVersioningRules, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateWorkerVersioningRules indicates an expected call of UpdateWorkerVersioningRules.
func (mr *MockClientMockRecorder) UpdateWorkerVersioningRules(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWorkflow mocks base method.
func (m *MockClient) UpdateWorkflow(ctx context.Context, options client.UpdateWorkflowOptions) (client.WorkflowUpdateHandle, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowUpdateHandle), nil
}

// UpdateWorkflow indicates an expected call of UpdateWorkflow.
func (mr *MockClientMockRecorder) UpdateWorkflow(ctx, options interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WorkflowService mocks base method.
func (m *MockClient) WorkflowService() workflowservice.WorkflowServiceClient {
	_ = "STUB: not implemented"
	return *new(workflowservice.WorkflowServiceClient)
}

// WorkflowService indicates an expected call of WorkflowService.
func (mr *MockClientMockRecorder) WorkflowService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockCloudOperationsClient is a mock of CloudOperationsClient interface.
type MockCloudOperationsClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudOperationsClientMockRecorder
}

// MockCloudOperationsClientMockRecorder is the mock recorder for MockCloudOperationsClient.
type MockCloudOperationsClientMockRecorder struct {
	mock *MockCloudOperationsClient
}

// NewMockCloudOperationsClient creates a new mock instance.
func NewMockCloudOperationsClient(ctrl *gomock.Controller) *MockCloudOperationsClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudOperationsClient) EXPECT() *MockCloudOperationsClientMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockCloudOperationsClient) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockCloudOperationsClientMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloudService mocks base method.
func (m *MockCloudOperationsClient) CloudService() cloudservice.CloudServiceClient {
	_ = "STUB: not implemented"
	return *new(cloudservice.CloudServiceClient)
}

// CloudService indicates an expected call of CloudService.
func (mr *MockCloudOperationsClientMockRecorder) CloudService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockNamespaceClient is a mock of NamespaceClient interface.
type MockNamespaceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceClientMockRecorder
}

// MockNamespaceClientMockRecorder is the mock recorder for MockNamespaceClient.
type MockNamespaceClientMockRecorder struct {
	mock *MockNamespaceClient
}

// NewMockNamespaceClient creates a new mock instance.
func NewMockNamespaceClient(ctrl *gomock.Controller) *MockNamespaceClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceClient) EXPECT() *MockNamespaceClientMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockNamespaceClient) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockNamespaceClientMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Describe mocks base method.
func (m *MockNamespaceClient) Describe(ctx context.Context, name string) (*workflowservice.DescribeNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Describe indicates an expected call of Describe.
func (mr *MockNamespaceClientMockRecorder) Describe(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Register mocks base method.
func (m *MockNamespaceClient) Register(ctx context.Context, request *workflowservice.RegisterNamespaceRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Register indicates an expected call of Register.
func (mr *MockNamespaceClientMockRecorder) Register(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockNamespaceClient) Update(ctx context.Context, request *workflowservice.UpdateNamespaceRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Update indicates an expected call of Update.
func (mr *MockNamespaceClientMockRecorder) Update(ctx, request interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
